from .submodels.faq import Faq
from .submodels.about import About
from .submodels.slider import Slider
from .submodels.why_choose_us import ChooseUs
from .submodels.support import Support
from .submodels.team import Founder
from .submodels.brand import Brand
from .submodels.contact import Contact
from .submodels.newsletter import NewsletterUser
from .submodels.offer import Offer
from .submodels.setting import Setting
from .submodels.social import Social
